version: '3'

services:
  postgres-market-data-btcusd:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_database
    container_name: postgres-market-data-btcusd
    ports:
      - "5432:5432"
      
  python-app-market-data-btcusd:
    build: ./app/
    volumes:
      - ./app:/app
    depends_on:
      - postgres-market-data-btcusd
    container_name: python-app-market-data-btcusd


volumes:
  db-data:

